export const getDataofertasApi = [
{
    id: '10201',
    name: 'Dell Inspiron 5620',
    description: 'Laptop de 16", teclado retroiluminado, Core i7 16 GB de RAM, DD de 1 TB SSD',
    price: 2399.99,
    category: 'Electronica',
    subcategory: 'laptop',
    marca: 'Dell',
    img: 'https://m.media-amazon.com/images/I/71TEO8sUk7L.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    url: '',
    dscto: '30%'
},
{
    id: '10202',
    name: 'Dell Inspiron 5620',
    description: 'SAMSUNG Monitor de computadora FHD 1080p de la serie T350 de 22 pulgadas, 75Hz, panel IPS, HDMI, VGA (D-Sub), sin bordes de 3 lados, FreeSync',
    price: 99.99,
    category: 'Electronica',
    subcategory: 'Monitor',
    marca: 'Samsung',
    img: 'https://m.media-amazon.com/images/I/61B8Lq5NXmL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    url: 'https://www.amazon.com/-/es/SAMSUNG-computadora-pulgadas-FreeSync-LF22T350FHNXZA/dp/B08FNW672V?ref_=Oct_DLandingS_D_c8764ec3_2&th=1',
    dscto: '25%'
},
{
    id: '10203',
    name: 'Jumper Acme 3100',
    description: 'jumper Computadora portátil, CPU Intel N100 de cuatro núcleos, 16 GB de RAM 512 GB SSD, portátiles con pantalla FHD IPS de 16 pulgadas 1920 x 1200, 4 altavoces estéreo, mini HDMI, cámara web HD',
    price: 379.99,
    category: 'Electronica',
    subcategory: 'laptop',
    marca: 'Dell',
    img: 'https://m.media-amazon.com/images/I/71Kt53BkNjL._AC_SX679_.jpg',
    url: 'https://www.amazon.com/jumper-Computer-Quad-Core-1920x1200-Speakers/dp/B0CK2S47K2?pf_rd_r=5RKC7HD2GAZF5HJ4P007&pf_rd_t=Events&pf_rd_i=deals&pf_rd_p=2364d0f5-5054-4700-a4e8-74a53fead388&pf_rd_s=slot-14&ref=dlx_deals_gd_dcl_img_20_e421d466_dt_sl14_88&th=1',
    dscto: '18%'
},
{
    id: '10204',
    name: 'HUANUO Soporte de monitor doble',
    description: 'HUANUO Soporte de monitor doble, soporte giratorio de escritorio con resorte ajustable, soporte giratorio Vesa con abrazadera C, base de montaje con ojales para pantallas de computadora de 13 a 27',
    price: 157.99,
    category: 'Electronica',
    subcategory: 'Accesorio',
    marca: 'HUANUO',
    img: 'https://m.media-amazon.com/images/I/71iCbWjCopL._AC_SL1500_.jpg',
    url: 'https://www.amazon.com/HUANUO-Dual-Monitor-Stand-Adjustable/dp/B07T5SY43L?pf_rd_r=5RKC7HD2GAZF5HJ4P007&pf_rd_t=Events&pf_rd_i=deals&pf_rd_p=2364d0f5-5054-4700-a4e8-74a53fead388&pf_rd_s=slot-14&ref=dlx_deals_gd_dcl_img_2_f2be7daa_dt_sl14_88',
    dscto: '30%'
},
{
    id: '10205',
    name: 'Mochila ',
    description: 'Mochila extra grande para laptop de viaje de 52 L con puerto de carga USB para portátiles de 17 pulgadas para hombres y mujeres',
    price: 27.99,
    category: 'Electronica',
    subcategory: 'laptop',
    marca: 'SHIRRADOO',
    img: 'https://m.media-amazon.com/images/I/61Ns-H-YLtL._AC_SY450_.jpg',
    url: 'https://www.amazon.com/Travel-Laptop-Backpack-Charging-Laptops/dp/B07V4R4Z77?pf_rd_r=5RKC7HD2GAZF5HJ4P007&pf_rd_t=Events&pf_rd_i=deals&pf_rd_p=2364d0f5-5054-4700-a4e8-74a53fead388&pf_rd_s=slot-14&ref=dlx_deals_gd_dcl_img_21_b18e868f_dt_sl14_88&th=1',
    dscto: '25%'
},
{
    id: '10206',
    name: 'Inphic mouse inalámbrico',
    description: 'Inphic mouse inalámbrico recargable, silencioso, mini mouse óptico ultrafino 1600 DPI para notebook, PC, laptop, computadora, MacBook (plateado), Plateado',
    price: 9.99,
    category: 'Electronica',
    subcategory: 'Mouse',
    marca: 'Inphic',
    img: 'https://m.media-amazon.com/images/I/71oFC2ZwKCL._AC_SY450_.jpg',
    url: 'https://www.amazon.com/Wireless-inphic-Rechargeable-Receiver-Black/dp/B074M96FKW?pf_rd_r=5RKC7HD2GAZF5HJ4P007&pf_rd_t=Events&pf_rd_i=deals&pf_rd_p=2364d0f5-5054-4700-a4e8-74a53fead388&pf_rd_s=slot-14&ref=dlx_deals_gd_dcl_img_32_cc744d33_dt_sl14_88&th=1',
    dscto: '30%'
},
{
    id: '10207',
    name: 'Tomtoc Bolsa organizadora ',
    description: 'Tomtoc Bolsa organizadora de cables de viaje, organizador de accesorios electrónicos, portátil, impermeable, doble accesorio para cable, cargador, cables, unidad USB, color negro',
    price: 24.99,
    category: 'Electronica',
    subcategory: 'Accesorio',
    marca: 'Tomtoc',
    img: 'https://m.media-amazon.com/images/I/81MHB4ifZ8L._AC_SY450_.jpg',
    url: 'https://www.amazon.com/tomtoc-Organizer-Electronics-Accessories-Waterproof/dp/B0CCP69CWW?pf_rd_r=X54QSCDYWFAB2M3P3WCQ&pf_rd_t=Events&pf_rd_i=deals&pf_rd_p=2364d0f5-5054-4700-a4e8-74a53fead388&pf_rd_s=slot-14&ref=dlx_deals_gd_dcl_img_168_3ebeeb9b_dt_sl14_88&th=1',
    dscto: '30%'
},
{
    id: '10208',
    name: 'TOZO A1 Mini auriculares inalámbricos',
    description: 'TOZO A1 Mini auriculares inalámbricos Bluetooth de 5.3 pulgadas, micrófono integrado, IPX5 impermeable, sonido inmersivo de alta calidad, conexión de larga distancia con funda de carga, color negro',
    price: 15.99,
    category: 'Electronica',
    subcategory: 'Accesorio',
    marca: 'Tozo',
    img: 'https://m.media-amazon.com/images/I/71Sqg+w9bFL._AC_SY450_.jpg',
    url: 'https://www.amazon.com/TOZO-A1-Light-Weight-Headphones-Microphone/dp/B09FT58QQP?pf_rd_r=X54QSCDYWFAB2M3P3WCQ&pf_rd_t=Events&pf_rd_i=deals&pf_rd_p=2364d0f5-5054-4700-a4e8-74a53fead388&pf_rd_s=slot-14&ref=dlx_deals_gd_dcl_img_196_c1a9ed6d_dt_sl14_88&th=1',
    dscto: '45%'
},
{
    id: '10209',
    name: 'BERIBES',
    description: 'Auriculares Bluetooth sobre la oreja, BERIBES 65H tiempo de reproducción y 6 modos de música ecualizador con micrófono, auriculares inalámbricos plegables estéreo HiFi ligeros, graves profundos',
    price: 21.58,
    category: 'Electronica',
    subcategory: 'Accesorio',
    marca: 'BERIBES',
    img: 'https://m.media-amazon.com/images/I/61bnUaDGWPL._AC_SY450_.jpg',
    url: '',
    dscto: '45%'
},
{
    id: '10210',
    name: 'OBSBOT Tiny 2 Webcam 4K',
    description: 'OBSBOT Tiny 2 Webcam 4K Control de voz PTZ, seguimiento AI multimodo y enfoque automático, cámara web con sensor de 1/1.5 pulgadas, control de gestos, 60 FPS, corrección de luz HDR, cámara web',
    price: 296.99,
    category: 'Electronica',
    subcategory: 'Accesorio',
    marca: 'OBSBOT',
    img: 'https://m.media-amazon.com/images/I/51XeBqiCrRL._AC_SX466_.jpg',
    url: 'https://www.amazon.com/OBSBOT-Multi-mode-Correction-Streaming-Conference/dp/B0C3B6ZR1V?pf_rd_r=VCA2GNFJSN9SMMHXDM6Y&pf_rd_t=Events&pf_rd_i=deals&pf_rd_p=2364d0f5-5054-4700-a4e8-74a53fead388&pf_rd_s=slot-14&ref=dlx_deals_gd_dcl_img_38_a3b94b83_dt_sl14_88&th=1',
    dscto: '30%'
},
{
    id: '10211',
    name: 'Dell Inspiron 5620',
    description: 'Laptop de 16", teclado retroiluminado, Core i7 16 GB de RAM, DD de 1 TB SSD',
    price: 2399.99,
    category: 'Electronica',
    subcategory: 'laptop',
    marca: 'Dell',
    img: 'https://m.media-amazon.com/images/I/71TEO8sUk7L.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    url: '',
    dscto: '20%'
},
{
    id: '10212',
    name: 'Dell Inspiron 5620',
    description: 'Laptop de 16", teclado retroiluminado, Core i7 16 GB de RAM, DD de 1 TB SSD',
    price: 2399.99,
    category: 'Electronica',
    subcategory: 'laptop',
    marca: 'Dell',
    img: 'https://m.media-amazon.com/images/I/71TEO8sUk7L.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    url: '',
    dscto: '20%'
}

]
